const products = [
    {
        sl: 1,
        name: "Sunny Health & Fitness Treadmill",
        img: "https://i.ibb.co/GHTdnLk/01-Sunny-Health-Fitness-Treadmill.jpg",
        brand: "Sunny Health & Fitness",
        totalRatings: 1580,
        ourRatings: 5,
        price: 480,
        dis: "Sunny Health & Fitness Treadmill is a new standard in home fitness! The SF-T4400 Treadmill offers all of the necessities for a marvelous cardio workout along with and everything all at-home fitness admirers could wish for. It will fresh your cardio moving and gives you a happy life.",
        glance_1: "2.20 Peak HP drive system ",
        glance_2: "It has 15.75in x 48.82 in running space ",
        glance_3: "Soft drop technology to help you unfold your treadmill accurately Easy folding mechanism ",
        glance_4: "Handrail controls will help you to control speed, start and  stop 9 Built-in workout programs",
        glance_5: "Pause function - Press the stop button once to stop the belt and pause your run while keeping your current data and running stats intact",
        glance_6: "large LCD display and smart phone/tablet holder"
    },


    {
        sl: 2,
        name: "Sunny Health & Fitness SF-T7603 Electric Treadmill",
        img: "https://i.ibb.co/6cM4ZTj/02-Sunny-Health-Fitness-SF-T7603-Electric-Treadmill.jpg",
        brand: "Sunny Health & Fitness",
        totalRatings: 540,
        ourRatings: 4.5,
        price: 427,
        dis: "Sunny Health & Fitness SF-T7603 Electric Treadmill is a ultra-mobile electric treadmill. The best LCD displays time, distance, speed, and calories, and users can choose from 9 built-in programs and 3 adjustable incline levels to further track and tailor their running experience. It has a soft-drop system and folding mechanism allow this treadmill to be easily and safely moved and folded without any bother.Sunny Health & Fitness SF - T7603 Electric Treadmill gives highest priorities to support and satisfaction of our customer",
        glance_1: "2.2HP peak DC motor",
        glance_2: "Along with a 16x49 inch running surface",
        glance_3: "Soft drop technology to help you unfold your treadmill accurately and with comfort",
        glance_4: "Handrail controls will help you to control speed, start and stop and calculate your pulse rate",
        glance_5: "9 built-in user programs with 3 adjustable levels of incline",
        glance_6: "Product extent: 62L x 27W x 47H inches"
    },

    {
        sl: 3,
        name: "Sunny Health & Fitness SF-T7514 Heavy Duty Walking Treadmill",
        img: "https://i.ibb.co/LY6NzLG/03-Sunny-Health-Fitness-SF-T7514-Heavy-Duty-Walking-Treadmill.jpg",
        brand: "Sunny Health & Fitness",
        totalRatings: 120,
        ourRatings: 3.75,
        price: 980,
        dis: "Sunny Health & Fitness SF-T7514 Heavy Duty Walking Treadmill  is the new standard in home fitness. It offers all of the necessities for an amazing cardio workout that all at-home fitness enthusiasts could wish for. It is included with a newly improved and quieter electromagnetic tension system, minimum speed 0.5 MPH and a maximum speed 4 MPH, 46 L in x 20 W in walking surface, Large LCD display will shows Time, Speed, Distance, Calories Burn and Pulse and 3 manual incline positions",
        glance_1: "46L x 20 W running surface & Shock Absorption system Electromagnetic tension system ",
        glance_2: "Large LCD display will show speed, time, distance, calories, and pulse with 12 Built-in workout programs",
        glance_3: "Start, stop, adjust speeds, and measure of your pulse is easily controlled by Handrail. ",
        glance_4: "Cushioned handrails with pulse grip heart rate monitoring",
        glance_5: "Extra wide heavy duty walking treadmill",
        glance_6: "Easy folding for storage "
    },

    {
        sl: 4,
        name: "ProForm ZT6 Treadmill",
        img: "https://i.ibb.co/bRQHywx/04-Pro-Form-ZT6-Treadmill.jpg",
        brand: "ProForm",
        totalRatings: 386,
        ourRatings: 4.75,
        price: 320,
        dis: "There is an assist that prevents it from dropping and crashing, but the belt assembly is still somewhat heavy. That said the design for the locking latch is well placed so you can use one hand to unlock while supporting the weight with you other hand before beginning to lower the belt. ",
        glance_1: "2.5 CHP Mach Z Commercial Motor",
        glance_2: "ProShox Cushioning",
        glance_3: "Space Saver Design & 5 Backlit Display",
        glance_4: "10 MPH Quick Speed Control, 10% Quick Incline Control, 18 Workout Apps, ",
        glance_5: "Grip Pulse EKG Heart Rate Monitor",
        glance_6: "This Treadmill belongs to a Lifetime Frame Warranty, 25-Year Motor Warranty and 1-Year Parts & Labor Warranty"
    },

    {
        sl: 5,
        name: "ProForm Pro 2000 Treadmill",
        img: "https://i.ibb.co/SBzp5mN/05-Pro-Form-Pro-2000-Treadmill.jpg",
        brand: "ProForm",
        totalRatings: 810,
        ourRatings: 5,
        price: 1499,
        dis: "ProForm Pro 2000 Treadmill was Built on 30 years of fitness engineering and technology, this treadmill is designed to burn more calories, improve real-road conditioning, and boost cardio endurance. So your health, your family, and your home get exactly what they need.",
        glance_1: "3.5 CHP Mach Z Commercial Pro Motor, 7 Oversized Backlit Display,  iFit Compatible, ",
        glance_2: "Compatible Music Port for iPod",
        glance_3: "12 MPH QuickSpeed Control, -3% Quick Decline Control, 15% Quick Incline Control, ",
        glance_4: "32 Workout Apps",
        glance_5: "2.5 Precision Machined and Balanced Non-Flex Rear Roller,  Cool Aire Workout Fan",
        glance_6: "friendly iFit Live Technology "
    },

    {
        sl: 6,
        name: "ProForm Performance 300i Treadmill",
        img: "https://i.ibb.co/sK6Qw8K/06-Pro-Form-Performance-300i-Treadmill.jpg",
        brand: "ProForm",
        totalRatings: 251,
        ourRatings: 4.25,
        price: 949,
        dis: "In ProForm Performance 300i Treadmill the 2.0 continuous horsepower motor delivers smooth, consistent power to every workout. A certified personal Trainer built to endure light and intense workouts, with this treadmill you can choose from eight preset workout apps. you'll see outcome fast with calorie or time based goals. Boost your speed incrementally up to 10 mph for added cardio benefits.",
        glance_1: "Space Saver Design ",
        glance_2: "2.0 CHP Drive System ",
        glance_3: "Large 1 Window LCD display ",
        glance_4: "ProShox Cushioning",
        glance_5: "Large 41 x 127 cm running area, an incline range of 0 - 10% ",
        glance_6: "2 Year parts and labour, 5 year motor, Lifetime frame guarantee"
    },

    {
        sl: 7,
        name: "ProForm ZT8 Treadmill",
        img: "https://i.ibb.co/bLLzBc7/07-A-Pro-Form-PFTL99715-Power-995i-Exercise-Treadmill-Graphite-Large.jpg",
        brand: "ProForm",
        totalRatings: 372,
        ourRatings: 3.50,
        price: 499,
        dis: "ProForm ZT8 Treadmill has never been as rewarding as it is with the ProForm ZT6 Treadmill. This Treadmill has an extra smooth 2.50-HP motor with a ProShox lite Cushioning Deck and digital quick speed electronics with incline adjust from 0-10 MPH and it is designed to give you the workout you'd pay to get at the gym – and more. The 6-inch backlit LCD display provides your time, distance, and speed so you can keep track of your progress. ",
        glance_1: "2.75 CHP Mach Z Motor, 20" x 60" 2-Ply ",
        glance_2: "22 Workout Apps, CoolAire Workout Fan, Grip Pulse EKG Heart Rate Monitor, 325 Lb. Weight Capacity",
        glance_3: "IFit Compatible; Requires iFit wireless module; sold separately; Buy an iFit wireless module and receive a free one-year iFit subscription",
        glance_4: "Space Saver Design with Easy Lift Assist",
        glance_5: "Compatible Music Port for iPod, ",
        glance_6: "The ProForm? ZT8 Treadmill is protected with a Lifetime Frame & Motor, 2-Year Parts and 1-Year Labor Warranty"
    },

    {
        sl: 8,
        name: "ProForm Performance 400i Treadmill",
        img: "https://i.ibb.co/ZM80CQY/08-Pro-Form-Performance-400i-Treadmill.jpg",
        brand: "ProForm",
        totalRatings: 369,
        ourRatings: 4.75,
        price: 730,
        dis: "ProForm Performance 400i Treadmill is great for all levels of training. Your speed, intermission and patience workouts are taken care of the powerful 2.5 CHP Mach Z motor. Certified personal trainers designed 18 programs. Stay in the right cardio zone with the EKG grip pulse heart rate monitor. And get better faster with the ProShox cushioning that reduces collision on your joints at every step of your running.",
        glance_1: "Heavy-duty treadmill accommodates up to 115 Kg., 25 chp Mach Z motor, ",
        glance_2: "20 x 55 tread belt, 19 inch length, Space saver design",
        glance_3: "18 workout Apps Proshox cushioning, ",
        glance_4: "Grip Pulse EKG heart RATE monitor",
        glance_5: "Compatible music port for IPod, IPod is a trademark of Apple, inc, registered in the US And other countries; IPod not included",
        glance_6: "The ProForm performance 400 Treadmill is protected with a Lifetime frame Warranty, 25-year motor Warranty and 1-Year parts and Labor Warranty"
    },

    {
        sl: 9,
        name: "NordicTrack C 1650 Treadmill",
        img: "https://i.ibb.co/CwmhgXT/09-Nordic-Track-C-1650-Treadmill.jpg",
        brand: "NordicTrack",
        totalRatings: 1120,
        ourRatings: 5,
        price: 934,
        dis: "The C1650 Treadmill features a stable bracket that secures your tablet at eye level above the console to deliver your favorite Entertainment while you train. Moreover you will get a 10-inch touch screen show offers your most wanted websites, workout stats, and Google maps workouts from if it technology to take your training on the highway.",
        glance_1: "Quickly view your speed, time, distance, calories burned, heart rate, incline, and decline on the large, easy-to-read display",
        glance_2: "Stay in Control of your workout with an impressive 10-inch web-enabled touch screen. ",
        glance_3: "Built with a bigger motor case for less shaking and dual cooling fans for less heat, this 3.5 nonstop horsepower motor delivers lasting power that's silky and constant",
        glance_4: "Plug your iPod into the console sound System and stay motivated with your workout playlist.",
        glance_5: " Ditch your ear buds for incredible sound from dual 2-inch speakers, 34 workout Apps.Get professional training with 34 preloaded  workouts designed by certified personal trainers",
        glance_6: "Choose from calorie, heart rate Control, incline, and speed workout programs"
    },

    {
        sl: 10,
        name: "Sole Fitness S77 Non-Folding Treadmill",
        img: "https://i.ibb.co/mSYSs4B/10-S77-Non-Folding-Treadmill.jpg",
        brand: "Sole",
        totalRatings: 4000,
        ourRatings: 5,
        price: 1450,
        dis: "The S77 treadmill gives everything you need in the ease of your own home. Its features a 4.0 Cont. Duty HP motor and also incorporates the largest deck SOLE offers, an exceptional 22 wide running surface that is great for any walker or runner.With the heart rate programs, the treadmill automatically makes managed to the incline to keep you in your target heart- rate zone.The included of wireless chest strap touts a 99.9 - Percent correctness rating.The treadmill motor deals with a full 30 - year warranty, with a lifetime warranty on the deck and frame.The comfort displays the ten available programs and has built in speakers which allow you to hook up any MP3 player, iPod, etc. ",
        glance_1: "Nine-inch LCD workout display",
        glance_2: "Running surface measures 22 by 60 inches (W x D",
        glance_3: "Pulse grip and chest strap heart rate monitoring",
        glance_4: "Nine-inch LCD workout display",
        glance_5: "Deck measures 30 by 80 inches (W x D)",
        glance_6: "Choose from calorie, heart rate Control, incline, and speed workout programs"
    },

    {
        sl: 11,
        name: "LifeSpan TR4000i Folding Treadmill",
        img: "https://i.ibb.co/Kzmbxfc/11-Life-Span-TR4000i-Folding-Treadmill.jpg",
        brand: "LifeSpan",
        totalRatings: 1720,
        ourRatings: 2244,
        price: 1890,
        dis: "the TR4000i folding treadmill is operational with performance-tuned hardware and sharp, fitness-tracking technology. It is designed to take your workout as seriously as you do.  A 3.25 hp motor and trustworthy all-steel frame provide perfect running/walking situation for any workout, mile after mile.  An Bluetooth adapter syncs your exercise data directly to your Smartphone, putting you in better control than always.",
        glance_1: "EZfold technology utilizes a hydraulic shock to assist in folding and unfolding the treadmill",
        glance_2: "800-pound maximum lift inclne motor",
        glance_3: "The 20 x 56 inch running surface features 8 impact-absorbing compression shocks to guarantee a consistently comfortable workout",
        glance_4: "6 Blue backlit LCD displays: time, calories, distance, steps, heart rate, speed, and incline level",
        glance_5: "Speed range of 0.5 to 12 mph, ",
        glance_6: "Lifetime frame and motor warranty; 5 year parts; 1 year labor warranty"
    },

    {
        sl: 13,
        name: "Confidence Fitness Magnetic Manual Treadmill",
        img: "https://i.ibb.co/yqKTd0f/13-Confidence-Fitness-Magnetic-Manual-Treadmill.jpg",
        brand: "Confidence",
        totalRatings: 672,
        ourRatings: 4.75,
        price: 1199,
        dis: "The Confidence Fitness Magnetic Manual Treadmill gives supreme value for those who want to work out in the ease of their home. It has 8 adjustable magnetic resistance levels and a simple folding or storage mechanism; this is the ideal personal running instrument.",
        glance_1: "Quiet and smooth magnetic resistance ",
        glance_2: "8 adjustable levels to tailor your workout level. ",
        glance_3: "Multi-function computer including speed, distance, calories, odometer, time and scan functions",
        glance_4: "Easily transported and stored – simple locking pin mechanism with built in wheels for ease of movement",
        glance_5: "Suitable for users up to 220lbs. ",
        glance_6: "12 month warranty"
    },
    {
        sl: 12,
        name: "LifeSpan TR3000i Folding Treadmill",
        img: "https://i.ibb.co/Y3ftQXZ/12-Life-Span-TR3000i-Folding-Treadmill.jpg",
        brand: "LifeSpan",
        totalRatings: 335,
        ourRatings: 4.75,
        price: 275,
        dis: "LifeSpan TR3000i Folding Treadmill is the perfect complement of capable, space-saving expertise and heart-monitoring hardware. Getting you moving towards your goals safer and with less time via Quick, EZfold assisted folding makes both storage and unfolding a snap. An Bluetooth-receiver syncs your exercise data straightly to your Smartphone, you may control better than ever. It is also USB Plus data to charge your mobile devices as well as save your exercise fallout to a USB drive for easy upload into your free club account.",
        glance_1: "Simple to lift and easy to lower ",
        glance_2: "EZfold technology utilizes a hydraulic shock to assist in folding and unfolding the treadmill",
        glance_3: "Features 15 incline levels, ",
        glance_4: "Speed range of 0.5 to 12 mph, ",
        glance_5: "2.75 HP continuous-duty DC motor ",
        glance_6: "Lifetime frame and motor warranty; 5 year parts; 1 year labor warranty"
    },
    {
        sl: 14,
        name: "Schwinn 830 Treadmill",
        img: "https://i.ibb.co/0YzgShk/14-Schwinn-830-Treadmill.jpg",
        brand: "Schwinn",
        totalRatings: 335,
        ourRatings: 5,
        price: 987,
        dis: "Schwinn 830 Treadmill is powered by a 2.75 CHP motor and 22 workout programs. It features is soft track cushioning system to deliver unparalleled comfort for a smooth workout experience. It has an extra high resolution display with a blue backlit LCD monitor to easily keep track of your workout time, distance and calories burned. The USB port allows you to use you won Media device and easily upload your running results to Schwinn connect and my fitness pall.",
        glance_1: "Extra-large high-resolution blue backlit LCD monitor",
        glance_2: "Everything to meet your fitness goals: 0 to 12 mph ",
        glance_3: "0 to 12% incline",
        glance_4: "20-Inch x 55-Inch belt",
        glance_5: "22 programs",
        glance_6: "Acoustic chambered speakers for big sound"
    },
    {
        sl: 15,
        name: "Nautilus T614 Treadmill",
        img: "https://i.ibb.co/vVqG3z3/15-Nautilus-T614-Treadmill.jpg",
        brand: "Nautilus",
        totalRatings: 650,
        ourRatings: 3.5,
        price: 1000,
        dis: "Nautilus T614 Treadmill is powered by a 2.75Chp motor and 22 workout programs. This treadmill features strike zone cushioning system to make you comfort and smoothly run. A high resolution display with blue back light LCD monitor will help you to monitor your workout time, distance and calories burned. With the addition of a media mantelpiece, You can now put a magazine, tablet and a book in front of you while running",
        glance_1: "Extra-large high-resolution blue backlit LCD monitor",
        glance_2: "Everything to meet your fitness goals: 0 to 12 MPH, ",
        glance_3: "2 user profiles and more",
        glance_4: "Acoustic chambered speakers for big sound",
        glance_5: "2.5-Inch crowned rollers, Soft Drop folding system, ",
        glance_6: "Warranty: 10 years on the frame and drive system, 2 years on parts, and 1 year on labor"
    },
    {
        sl: 16,
        name: "Merit Fitness 715T Plus Treadmill",
        img: "https://i.ibb.co/M6vN5CC/16-Merit-Fitness-715-T-Plus-Treadmill.jpg",
        brand: "Merit Fitness",
        totalRatings: 1194,
        ourRatings: 5,
        price: 510,
        dis: "The Merit 715T Plus is definitely a treadmill for beginners only. To help people exercise efficiently, it has three training programs that adjust the intensity of the challenge: Rolling Hills, Weight Loss and Interval. The treadmill can also be used in manual mode for alternating between speeds up to 10 mph. LCD monitor to easily keep track of your workout time, heart rate, distance, speed and calories burned. In this treadmill we found some attractive points, but overall we recommend saving your hard-earned cash for a more durable alternative.",
        glance_1: "Home treadmill with top-quality 2.5 THP (1.5 CHP) drive motor",
        glance_2: "Intuitive console controls with adjustable speed from 0 to 10 miles per hour",
        glance_3: "3-window LED display tracks your time, speed, distance, calories, and more",
        glance_4: "Heart Rate Monitor",
        glance_5: "4. Pre-set Workout Programs",
        glance_6: "12 months warinty"
    },
    {
        sl: 17,
        name: "Schwinn 870 Treadmill",
        img: "https://i.ibb.co/G58xSmW/17-Schwinn-870-Treadmill.jpg",
        brand: "Schwinn",
        totalRatings: 1241,
        ourRatings: 5,
        price: 250,
        dis: "Schwinn 870 Treadmill is the top of the line treadmill features 3.0CHP motor. 26 workout programs and dual track display that provides two high resolutions. Blue back light LCD monitor, so you can stay informed while reading a magazine or watching your tablet. It also included a USB media charging, an MP3 input port, in-console speakers. So all the way it is the best treadmill for the user. ",
        glance_1: "Charging USB port and data export to schwinnconnect.com or myfitnesspal.com",
        glance_2: "Blue backlit Dual Track LCD display - two LCD windows display the status",
        glance_3: "Speed: 0 to 12 MPH, ",
        glance_4: "0 to 15% incline, ",
        glance_5: "3.0 CHP motor, ",
        glance_6: "20-Inch x 60-Inch belt, "
    },
    {
        sl: 18,
        name: "Nautilus T616 Treadmill",
        img: "https://i.ibb.co/HDBqg3m/18-Nautilus-T616-Treadmill.jpg",
        brand: "Nautilus",
        totalRatings: 2124,
        ourRatings: 5,
        price: 1582,
        dis: "Nautilus T616 Treadmill with a 3.0 CHP motor, large 2.75 inch crown rollers and a roomy running surface of 20″ x 60″, the T616 is both comfortable and well-made. It is also a folding instrument, equipped with a soft drop folding design. This Treadmill is all about convenience and ease. In adding up to the folding design and spacious running area, this model is also designed with cushioning System, 6 hex cell designs, for extra comfort. You can enjoy an incline from 0 to 15% and speeds from 0 to 12 mph, and the weight ability tops out at 300 pounds.",
        glance_1: "Blue backlit Dual Track LCD display - two LCD windows display the status up to 13 workout details",
        glance_2: "Bluetooth LE connectivity and Charging USB port",
        glance_3: "Speed: 0 to 12 MPH, ",
        glance_4: "Acoustic chambered speakers for big sound",
        glance_5: " 3.0 CHP motor, ",
        glance_6: "Soft Drop folding system, "
    },


]